### ISSUE TITLE
If pmvs dir exists already the script should prompt the user to remove it

### ISSUE THREAD

**Issue by rjanvier** [archeos/ppt-archeos#2]
All is in the title.

**Comment by alearcteam** [comment]
yes, could be very usefull.

**Comment by rjanvier** [comment]
Default behavior (in package 0archeos1) is now to remove pmvs directory anyway. Prompting user is a bad idea because we should be able to run ppt with ppt-gui. Using command line input in the gui could be ineffective. Here is some envisaged solutions:
-Remove pmvs dir by default (actual behavior in package 0archeos1)
-Move the old pmvs dir (with an Hash) 
-Add a flag on command line to 'force remove' if pmvs dir exists in the root of the project(and add a checkbox for this option in the ppt-gui)

**Comment by alearcteam** [comment]
i like the second and the third options. maybe the second one is easer for newbies.
Ale

**Comment by rjanvier** [comment]
I think it's good with the second option.
